---
- name: Import Microsoft GPG Key (apt)
  become: yes
  become_method: sudo
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code Repo (apt)
  become: yes
  become_method: sudo
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
    filename: vscode

- name: Install VS Code (apt)
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name: code
    state: present