#SPDX-License-Identifier: MIT-0
---
- name: ensure oh-my-zsh is installed
  become: yes
  become_user: "{{ target_user }}" 
  block:
  - name: Check if oh-my-zsh is installed
    stat:
      path: "~/.oh-my-zsh"
    register: ohMyZsh_dir_exists

  - name: Install
    when: not ohMyZsh_dir_exists.stat.exists
    block:
    - name: Clone repo
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ target_user }}/.oh-my-zsh"
        clone: yes

    - name: Copy zsh config
      copy:
        force: true
        src: "/home/{{ target_user }}/.oh-my-zsh/templates/zshrc.zsh-template"
        dest: "/home/{{ target_user }}/.zshrc"


