#SPDX-License-Identifier: MIT-0
---
# tasks file for ensureTargetUserExists
- name: Ensure my user exists
  become: yes
  become_method: sudo
  ansible.builtin.user:
    name: "{{ target_user }}"
    generate_ssh_key: false
    state: present
    update_password: on_create
    groups: "{{ user_groups }}"
    password: "{{ target_password }}"
    shell: /bin/zsh

- name: Create folders for mwagner
  become: yes
  become_user: "{{ target_user }}"
  file:
    name: "{{ item }}"
    state: directory
    recurse: yes
  loop: "{{ target_user_folders }}"
