#SPDX-License-Identifier: MIT-0
---
- name: Install packages and flatpack
  become: yes
  become_method: sudo
  block:
  - name: Install software packages (Common)
    ansible.builtin.package:
      name: "{{ packages_to_install }}"
      state: latest
      update_cache: false

  - name: Add flathub remote
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: Install flatpaks
    community.general.flatpak:
      name: "{{ flatpaks_to_install }}"
      state: latest