#SPDX-License-Identifier: MIT-0
---
# tasks file for enableDnf5
- name: Check and enable
  become: yes
  become_method: sudo
  block:
  - name: Detect pkg mgr
    set_fact:
      pkg_mgr_short: "{{ ansible_pkg_mgr [:3] }}"

  - name: Detected pkg mgr
    debug:
      msg: "Package mg: {{ pkg_mgr_short }}"

  - name: Ensure dnf5 will work on Fedora
    when: ansible_pkg_mgr is match("dnf.*")
    dnf:
      name: python3-libdnf5
      use_backend: "dnf4"
      state: latest